# Site settings
title: 
email: jobvandervoort at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  Job's website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jobvandervoort.com" # the base hostname & protocol for your site
twitter_username: Jobvo
github_username:  JobV

# Build settings
markdown: kramdown
